import type { ProductCreate } from "../utils/api-client";

/**
 * Canonical seeded accounts. Must match apps/backend/app/seeds/seed.py.
 * Override via env so the same suite can run against different fixtures.
 */
export const accounts = {
  admin: {
    email: process.env.SHOPLITE_ADMIN_EMAIL ?? "admin@shoplite.io",
    password: process.env.SHOPLITE_ADMIN_PASSWORD ?? "admin123",
  },
  user: {
    email: process.env.SHOPLITE_USER_EMAIL ?? "user@shoplite.io",
    password: process.env.SHOPLITE_USER_PASSWORD ?? "user1234",
  },
} as const;

let _counter = Date.now();
/** Monotonic per-process suffix so factory-built records don't collide. */
function uniqueSuffix(): string {
  return String(_counter++);
}

/** Build a product payload suitable for POST /api/admin/products. */
export function makeProduct(overrides: Partial<ProductCreate> = {}): ProductCreate {
  const id = uniqueSuffix();
  return {
    name: `QA Product ${id}`,
    description: `Generated by factory at ${new Date().toISOString()}`,
    price: "9.99",
    stock: 10,
    category: "qa-fixtures",
    image_url: "",
    ...overrides,
  };
}

/** Helper for tests that need to know what we seeded the canonical DB with. */
export const seededProductNames = [
  "Classic Tee",
  "Hooded Sweatshirt",
  "Denim Jeans",
  "Canvas Sneakers",
  "The Pragmatic Tester",
  "FastAPI in Action",
  "Designing Data Tests",
  "Playwright Patterns",
  "Wireless Mouse",
  "Mechanical Keyboard",
  "USB-C Hub",
  "Noise-Cancelling Headphones",
  '27" Monitor',
  "Ceramic Mug",
  "Scented Candle",
  "Throw Blanket",
  "Desk Lamp",
  "Single-Origin Coffee",
  "Artisan Chocolate Bar",
  "Olive Oil 500ml",
] as const;
